from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any


ENV_KEYS = [
    "SERPAPI_API_KEY",
    "BRAVE_API_KEY",
    "TAVILY_API_KEY",
    "SERPER_API_KEY",
    "FIRECRAWL_API_KEY",
    "EXA_API_KEY",
    "OPENAI_API_KEY",
    "DDGS_ENABLED",
    "FINDER_CACHE_DIR",
    "FINDER_HTTP_TIMEOUT",
    "FINDER_TAVILY_RAW_CONTENT",
    "FINDER_SECOND_PASS_MAX_FETCH_CANDIDATES",
    "FINDER_SECOND_PASS_RESCUE_FETCH_CANDIDATES",
    "FINDER_SECOND_PASS_EXA_QUERIES",
    "FINDER_AGENT_B_LLM_REVIEW",
    "FINDER_AGENT_B_LLM_MODEL",
]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create/update .env from local API key files without printing secrets.")
    parser.add_argument("--brave-key-file", required=True, help="Path to a file containing the Brave Search API key.")
    parser.add_argument("--exa-key-file", help="Path to a file containing the Exa API key.")
    parser.add_argument("--openai-key-file", help="Path to a file containing the OpenAI API key.")
    parser.add_argument("--env", default=".env", help="Target .env path. Default: .env in the repo root.")
    parser.add_argument("--example", default=".env.example", help="Template env file. Default: .env.example.")
    args = parser.parse_args(argv)

    brave = extract_key_from_file(args.brave_key_file, "BRAVE_API_KEY")
    exa = extract_key_from_file(args.exa_key_file, "EXA_API_KEY") if args.exa_key_file else ""
    openai = extract_key_from_file(args.openai_key_file, "OPENAI_API_KEY") if args.openai_key_file else ""
    if not brave:
        raise SystemExit("Could not extract BRAVE_API_KEY from the provided file.")

    env_path = Path(args.env)
    example_path = Path(args.example)
    values = read_env(example_path if example_path.exists() else None)
    if env_path.exists():
        values.update(read_env(env_path))
    values["BRAVE_API_KEY"] = brave
    if exa:
        values["EXA_API_KEY"] = exa
    if openai:
        values["OPENAI_API_KEY"] = openai
    values.setdefault("DDGS_ENABLED", "0")
    values.setdefault("FINDER_CACHE_DIR", ".cache")
    values.setdefault("FINDER_HTTP_TIMEOUT", "12")
    values.setdefault("FINDER_AGENT_B_LLM_REVIEW", "0")
    values.setdefault("FINDER_AGENT_B_LLM_MODEL", "gpt-4.1-mini")

    write_env(env_path, values)
    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass

    summary = {
        "env_path": str(env_path.resolve()),
        "brave_configured": bool(values.get("BRAVE_API_KEY")),
        "exa_configured": bool(values.get("EXA_API_KEY")),
        "openai_configured": bool(values.get("OPENAI_API_KEY")),
        "keys_printed": False,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


def extract_key_from_file(path: str | Path | None, env_name: str) -> str:
    if not path:
        return ""
    key_path = Path(path).expanduser()
    if not key_path.exists():
        raise FileNotFoundError(f"API key file does not exist: {key_path}")
    text = key_path.read_text(encoding="utf-8", errors="ignore").strip()
    if _looks_like_rtf(text):
        text = _rtf_to_text(text).strip()
    if not text:
        return ""

    json_value = _extract_from_json(text, env_name)
    if json_value:
        return json_value

    named_value = _extract_named_value(text, env_name)
    if named_value:
        return named_value

    secret_token = _extract_secret_token(text)
    if secret_token:
        return secret_token

    return _extract_plain_value(text)


def read_env(path: Path | None) -> dict[str, str]:
    if path is None:
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key:
            values[key] = _clean_value(value)
    return values


def write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ordered = [key for key in ENV_KEYS if key in values]
    ordered.extend(sorted(key for key in values if key not in set(ordered)))
    lines = [
        "# Generated by tools/configure_env_from_key_files.py.",
        "# Do not commit or share this file.",
    ]
    for key in ordered:
        lines.append(f"{key}={values.get(key, '')}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _extract_from_json(text: str, env_name: str) -> str:
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return ""
    aliases = {
        env_name,
        env_name.lower(),
        env_name.removesuffix("_API_KEY").lower(),
        "api_key",
        "apikey",
        "key",
        "token",
    }
    for value in _walk_json(data):
        if isinstance(value, tuple):
            key, item = value
            if str(key).strip() in aliases and isinstance(item, str):
                cleaned = _clean_value(item)
                if cleaned:
                    return cleaned
    return ""


def _walk_json(value: Any):
    if isinstance(value, dict):
        for key, item in value.items():
            yield (key, item)
            yield from _walk_json(item)
    elif isinstance(value, list):
        for item in value:
            yield from _walk_json(item)


def _extract_named_value(text: str, env_name: str) -> str:
    names = [env_name, env_name.lower(), env_name.removesuffix("_API_KEY").lower()]
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        for name in names:
            match = re.match(rf"^(?:export\s+)?{re.escape(name)}\s*[:=]\s*(.+)$", line, flags=re.IGNORECASE)
            if match:
                return _clean_value(match.group(1))
    return ""


def _extract_plain_value(text: str) -> str:
    for raw_line in text.splitlines():
        line = _clean_value(raw_line)
        if not line or line.startswith("#") or line.startswith("//"):
            continue
        if " " in line and "=" not in line and ":" not in line:
            continue
        if "=" in line:
            line = _clean_value(line.split("=", 1)[1])
        elif ":" in line and not line.lower().startswith(("http://", "https://")):
            line = _clean_value(line.split(":", 1)[1])
        if line:
            return line
    return ""


def _extract_secret_token(text: str) -> str:
    candidates = []
    for token in re.findall(r"[A-Za-z0-9][A-Za-z0-9_.-]{15,}", text):
        cleaned = _clean_value(token)
        if _is_secret_like_token(cleaned):
            candidates.append(cleaned)
    if not candidates:
        return ""
    candidates.sort(key=len, reverse=True)
    return candidates[0]


def _is_secret_like_token(value: str) -> bool:
    if len(value) < 16:
        return False
    lowered = value.casefold()
    blocked = {"helvetica", "courier", "times", "fonttbl", "colortbl"}
    if lowered in blocked or lowered.startswith(("http.", "https.", "www.")):
        return False
    if "." in value and not any(ch.isdigit() for ch in value):
        return False
    return bool(re.search(r"[A-Za-z]", value)) and bool(re.search(r"[0-9]", value))


def _clean_value(value: str) -> str:
    value = value.strip().strip(",")
    if "#" in value:
        value = value.split("#", 1)[0].strip()
    return value.strip().strip('"').strip("'").strip()


def _looks_like_rtf(text: str) -> bool:
    return text.lstrip().startswith("{\\rtf")


def _rtf_to_text(text: str) -> str:
    # API keys are ASCII; this lightweight RTF extraction avoids external tools and never prints the text.
    hex_bytes = bytearray()
    out: list[str] = []
    idx = 0
    while idx < len(text):
        ch = text[idx]
        if ch == "\\":
            if idx + 3 < len(text) and text[idx + 1] == "'" and re.fullmatch(r"[0-9a-fA-F]{2}", text[idx + 2 : idx + 4]):
                hex_bytes.append(int(text[idx + 2 : idx + 4], 16))
                idx += 4
                continue
            if hex_bytes:
                out.append(_decode_rtf_bytes(bytes(hex_bytes)))
                hex_bytes.clear()
            match = re.match(r"\\[a-zA-Z]+-?\d* ?", text[idx:])
            if match:
                idx += len(match.group(0))
                continue
            if idx + 1 < len(text):
                out.append(text[idx + 1])
                idx += 2
                continue
        if hex_bytes:
            out.append(_decode_rtf_bytes(bytes(hex_bytes)))
            hex_bytes.clear()
        if ch in "{}":
            idx += 1
            continue
        out.append(ch)
        idx += 1
    if hex_bytes:
        out.append(_decode_rtf_bytes(bytes(hex_bytes)))
    return re.sub(r"\s+", "\n", "".join(out))


def _decode_rtf_bytes(data: bytes) -> str:
    for encoding in ["utf-8", "gb18030", "cp1252", "latin-1"]:
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("latin-1", errors="ignore")


if __name__ == "__main__":
    raise SystemExit(main())
